services:
  db:
    image: postgres:latest
    container_name: medods_db
    environment:
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_USER: "postgres"
    networks:
      - inner_net
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD","pg_isready","-U","postgres"]
      interval: 10s
      retries: 5
  backend:
    build: .
    container_name: auth_service
    environment:
      DB_PASSWORD: "qwerty"
      HOST_PORT:  "8080"
      DB_HOST:  "medods_db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_NAME: "auth"
      DB_SSLMODE: "disable"

    networks:
      - inner_net
    ports:
      - "8082:8080"
    depends_on:
      - db
volumes:
  postgres_data:
networks:
  inner_net:
    driver: bridge